# Generated by Django 5.0 on 2024-01-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='preview',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='video_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
