# Generated by Django 5.0 on 2024-02-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0002_remove_recommendation_preview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinterest',
            options={'ordering': ('id',), 'verbose_name_plural': 'User Intrests'},
        ),
    ]
