# Generated by Django 3.2.24 on 2024-02-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0003_alter_userinterest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='source',
            field=models.CharField(choices=[['books', 'books'], ['youtube', 'youtube']], default='books', max_length=20),
        ),
    ]
