# Generated by Django 3.2.24 on 2024-02-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0005_recommendationnotes_usercontent_userrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontent',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
