# Generated by Django 3.2.24 on 2024-02-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0006_usercontent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
