# Generated by Django 3.2.24 on 2024-02-19 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0007_userreview_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontent',
            name='interest',
            field=models.ForeignKey(default=40, on_delete=django.db.models.deletion.CASCADE, related_name='user_content', to='interest.interest'),
            preserve_default=False,
        ),
    ]
