# Generated by Django 5.0 on 2024-02-21 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0008_usercontent_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='source',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='url',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='video_id',
        ),
        migrations.CreateModel(
            name='RecommendationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('video_id', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(choices=[('books', 'books'), ('youtube', 'youtube')], default='books', max_length=20)),
                ('thumbnail', models.URLField(default='')),
                ('title', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_videos', to='interest.recommendation')),
            ],
            options={
                'verbose_name_plural': 'Recommendation Videos',
                'ordering': ('-created_at',),
            },
        ),
    ]
