# Generated by Django 5.0 on 2024-02-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0009_remove_recommendation_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='playlist_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationvideo',
            name='source',
            field=models.CharField(choices=[('books', 'books'), ('youtube', 'youtube')], default='youtube', max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendationvideo',
            name='video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
