# Generated by Django 5.0 on 2024-02-21 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0010_recommendation_playlist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationnotes',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_notes', to='interest.recommendationvideo'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interest.recommendationvideo'),
        ),
    ]
