# Generated by Django 3.2.24 on 2024-02-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0011_alter_recommendationnotes_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationvideo',
            name='source',
            field=models.CharField(choices=[['books', 'books'], ['youtube', 'youtube']], default='youtube', max_length=20),
        ),
    ]
