# Generated by Django 5.0.3 on 2024-03-17 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0015_recommendationviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='recommendations',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='interest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interest.interest'),
        ),
    ]
