# Generated by Django 5.0.3 on 2024-03-17 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0016_remove_interest_recommendations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='interest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interest.interest'),
            preserve_default=False,
        ),
    ]
