# Generated by Django 5.0.3 on 2024-03-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0017_alter_recommendation_interest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRecommendation',
        ),
    ]
