# Generated by Django 5.0.3 on 2024-03-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0019_recommendationviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='review',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
