# Generated by Django 5.0.3 on 2024-04-01 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0020_alter_userreview_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='usercontent',
            name='content_type',
        ),
        migrations.CreateModel(
            name='UserContentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(blank=True, null=True, upload_to='user_content/')),
                ('content_type', models.CharField(choices=[('video', 'video'), ('pdf', 'pdf')], default='video', max_length=10)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interest.usercontent')),
            ],
            options={
                'verbose_name_plural': 'User Content Recommendations',
                'ordering': ('-created_at',),
            },
        ),
    ]
