# Generated by Django 5.0.3 on 2024-04-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0021_remove_usercontent_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontentrecommendation',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='user_content/thumbnail/'),
            preserve_default=False,
        ),
    ]
