# Generated by Django 3.2.24 on 2024-02-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.usergroup'),
            preserve_default=False,
        ),
    ]
