# Generated by Django 3.2.24 on 2024-02-26 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_groupmessage_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_message_member', to='chat.groupmember'),
        ),
    ]
