# Generated by Django 3.2.24 on 2024-02-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_groupmessage_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
