# Generated by Django 3.2.24 on 2024-03-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_groupmember_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='chat/'),
        ),
    ]
