# Generated by Django 3.2.24 on 2024-03-06 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_usergroup_on_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='GroupVoiceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.usergroup')),
                ('participants', models.ManyToManyField(related_name='voice_call_participants', to='chat.GroupMember')),
            ],
        ),
    ]
