# Generated by Django 5.0.3 on 2024-03-24 23:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_groupmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=30, unique=True),
        ),
    ]
