# Generated by Django 5.0.3 on 2024-03-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_groupmember_uid_alter_usergroup_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['name'], 'verbose_name': 'User Group', 'verbose_name_plural': 'User Groups'},
        ),
    ]
