# Generated by Django 5.0 on 2023-12-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
