# Generated by Django 5.0 on 2023-12-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_password_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='profiles/default.webp', upload_to='profiles/'),
        ),
    ]
