# Generated by Django 5.0 on 2024-01-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_reportedusers_reporteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
