# Generated by Django 5.0 on 2024-01-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteduser',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
