# Generated by Django 5.0 on 2024-02-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_usergroups_groupmembers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMembers',
            new_name='GroupMember',
        ),
        migrations.RenameModel(
            old_name='UserGroups',
            new_name='UserGroup',
        ),
    ]
