# Generated by Django 3.2.24 on 2024-02-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_groupmembers_groupmember_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='admin',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
